// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package strings

import (
	"strconv"
	"strings"
)

// ToI16 converts a string to a int16
// Use only when you don't care if the input is valid, as the error is thrown away.
// No efforts are made to handle overflow.
func ToI16(src string) int16 {
	num, _ := strconv.ParseInt(src, 10, 16)

	return int16(num)
}

// ToI16_FAST doesn't use the stdlib to convert numbers.
// It's "safe" if you don't expect negative integers, but really only
// saves 10-20 ns.
func ToI16_FAST(src string) int16 {
	var n int16

	for i := 0; i < len(src); i++ {
		n = n*10 + int16(src[i]-'0')
	}

	return n
}

// CsvToI16 converts a string to []int16, zero vals included.
func CsvToI16(src string) []int16 {
	if len(src) == 0 {
		return nil
	}

	split := strings.Split(src, ",")
	r := make([]int16, len(split))

	for i := 0; i < len(split); i++ {
		r[i] = ToI16(split[i])
	}

	return r
}

// StrsToI16 converts a []string to []int16.
func StrsToI16(src []string) []int16 {
	if len(src) == 0 {
		return nil
	}

	r := make([]int16, len(src))
	for i := range src {
		r[i] = ToI16(src[i])
	}

	return r
}
