// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package strings

import (
	"strconv"
	"strings"
)

// ToI32 converts a string to a int32
// Use only when you don't care if the input is valid, as the error is thrown away.
// No efforts are made to handle overflow.
func ToI32(src string) int32 {
	num, _ := strconv.ParseInt(src, 10, 32)

	return int32(num)
}

// ToI32_FAST doesn't use the stdlib to convert numbers.
// It's "safe" if you don't expect negative integers, but really only
// saves 10-20 ns.
func ToI32_FAST(src string) int32 {
	var n int32

	for i := 0; i < len(src); i++ {
		n = n*10 + int32(src[i]-'0')
	}

	return n
}

// CsvToI32 converts a string to []int32, zero vals included.
func CsvToI32(src string) []int32 {
	if len(src) == 0 {
		return nil
	}

	split := strings.Split(src, ",")
	r := make([]int32, len(split))

	for i := 0; i < len(split); i++ {
		r[i] = ToI32(split[i])
	}

	return r
}

// StrsToI32 converts a []string to []int32.
func StrsToI32(src []string) []int32 {
	if len(src) == 0 {
		return nil
	}

	r := make([]int32, len(src))
	for i := range src {
		r[i] = ToI32(src[i])
	}

	return r
}
