// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package strings

import (
	"fmt"
	"math"
	"math/rand"
	"testing"
)

var maxUInt32 = ^uint32(0)
var maxInt32 = int32(maxUInt32 >> 1)
var minInt32 = -(maxInt32 - 1)

func TestI32(t *testing.T) {
	numstr := "100"

	n := ToI32(numstr)
	if n != 100 {
		t.Error("Failed to get 100 from ToI32")
	}

	// we don't _really_ care if the string doesn't actually represent
	// a number. in that case, we just want a 0 back.
	invalid := "-_-f-ado039230_;lol_no<generics>"
	n = ToI32(invalid)
	if n != 0 {
		t.Errorf("Got %d from ToI32, expected 0", n)
	}
}

func TestCsvToI32(t *testing.T) {
	csvstr := fmt.Sprintf("%d,1,2,3,%d", minInt32, maxInt32)

	nslc := CsvToI32(csvstr)
	if nslc[0] != minInt32 || nslc[1] != 1 || nslc[2] != 2 || nslc[3] != 3 || nslc[4] != maxInt32 {
		t.Errorf("Failed to decode %s: got %v", csvstr, nslc)
	}

	invalid := "a,b,cDEf,4,5,6;7;8" // we'll expect some zeroes
	nslc = CsvToI32(invalid)
	if nslc[0] != 0 || nslc[1] != 0 || nslc[2] != 0 || nslc[3] != 4 || nslc[4] != 5 || nslc[5] != 0 {
		t.Errorf("Failed to decode %s: got %v", invalid, nslc)
	}
}

func TestStrsToI32(t *testing.T) {
	rstrs := _randBI32()
	strs := _toStrsI32(rstrs)

	nslc := StrsToI32(strs)

	for i := range nslc {
		if nslc[i] != rstrs[i] {
			t.Errorf("Expected nslc[%d] = randoms[%d]; got %v / %v", i, i, nslc[i], rstrs[i])
		}
	}

	t.Logf("%v == %v", strs, nslc)
}

func _randI32() int32 {
	m := math.Abs(math.Min(math.Pow(2, 32), math.Pow(2, 32)))

	return int32(rand.Intn(int(m)))
}

func _randBI32() []int32 {
	r := make([]int32, 10)

	for i := 0; i < len(r); i++ {
		r[i] = _randI32()
	}

	return r
}

func _toStrsI32(src []int32) []string {
	strs := make([]string, len(src))
	for i := range src {
		strs[i] = fmt.Sprintf("%d", src[i])
	}

	return strs
}

var I32_FAST int32

func BenchmarkFast_I32(b *testing.B) {
	var num int32
	// generate some random numbers
	x := make([]string, 1000)
	for i := 0; i < 1000; i++ {
		x[i] = fmt.Sprintf("%d", _randI32())
	}

	b.ResetTimer()
	b.ReportAllocs()

	for n := 0; n < b.N; n++ {
		num = ToI32_FAST(x[n*int(1000/b.N)])
	}

	I32_FAST = num
}

var I32_STD int32

func BenchmarkStdAtoi_I32(b *testing.B) {
	var num int32
	// generate some random numbers
	x := make([]string, 1000)
	for i := 0; i < 1000; i++ {
		x[i] = fmt.Sprintf("%d", _randI32())
	}

	b.ResetTimer()
	b.ReportAllocs()

	for n := 0; n < b.N; n++ {
		num = ToI32(x[n*int(1000/b.N)])
	}

	I32_STD = num
}
