// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package strings

import (
	"strconv"
	"strings"
)

// ToI64 converts a string to a int64
// Use only when you don't care if the input is valid, as the error is thrown away.
// No efforts are made to handle overflow.
func ToI64(src string) int64 {
	num, _ := strconv.ParseInt(src, 10, 64)

	return int64(num)
}

// ToI64_FAST doesn't use the stdlib to convert numbers.
// It's "safe" if you don't expect negative integers, but really only
// saves 10-20 ns.
func ToI64_FAST(src string) int64 {
	var n int64

	for i := 0; i < len(src); i++ {
		n = n*10 + int64(src[i]-'0')
	}

	return n
}

// CsvToI64 converts a string to []int64, zero vals included.
func CsvToI64(src string) []int64 {
	if len(src) == 0 {
		return nil
	}

	split := strings.Split(src, ",")
	r := make([]int64, len(split))

	for i := 0; i < len(split); i++ {
		r[i] = ToI64(split[i])
	}

	return r
}

// StrsToI64 converts a []string to []int64.
func StrsToI64(src []string) []int64 {
	if len(src) == 0 {
		return nil
	}

	r := make([]int64, len(src))
	for i := range src {
		r[i] = ToI64(src[i])
	}

	return r
}
