// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package strings

import (
	"strconv"
	"strings"
)

// ToU16 converts a string to a uint16
// Use only when you don't care if the input is valid, as the error is thrown away.
// No efforts are made to handle overflow.
func ToU16(src string) uint16 {
	num, _ := strconv.ParseUint(src, 10, 16)

	return uint16(num)
}

// ToU16_FAST doesn't use the stdlib to convert numbers.
// It's "safe" if you don't expect negative integers, but really only
// saves 10-20 ns.
func ToU16_FAST(src string) uint16 {
	var n uint16

	for i := 0; i < len(src); i++ {
		n = n*10 + uint16(src[i]-'0')
	}

	return n
}

// CsvToU16 converts a string to []uint16, zero vals included.
func CsvToU16(src string) []uint16 {
	if len(src) == 0 {
		return nil
	}

	split := strings.Split(src, ",")
	r := make([]uint16, len(split))

	for i := 0; i < len(split); i++ {
		r[i] = ToU16(split[i])
	}

	return r
}

// StrsToU16 converts a []string to []uint16.
func StrsToU16(src []string) []uint16 {
	if len(src) == 0 {
		return nil
	}

	r := make([]uint16, len(src))
	for i := range src {
		r[i] = ToU16(src[i])
	}

	return r
}
