// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package strings

import (
	"fmt"
	"math"
	"math/rand"
	"testing"
)

var maxUint32 = ^uint32(0)

func TestU32(t *testing.T) {
	numstr := "100"

	n := ToU32(numstr)
	if n != 100 {
		t.Error("Failed to get 100 from ToU32")
	}

	// we don't _really_ care if the string doesn't actually represent
	// a number. in that case, we just want a 0 back.
	invalid := "-_-f-ado039230_;lol_no<generics>"
	n = ToU32(invalid)
	if n != 0 {
		t.Errorf("Got %d from ToU32, expected 0", n)
	}
}

func TestCsvToU32(t *testing.T) {
	csvstr := fmt.Sprintf("0,1,2,3,%d", maxUint32)

	nslc := CsvToU32(csvstr)
	if nslc[0] != 0 || nslc[1] != 1 || nslc[2] != 2 || nslc[3] != 3 || nslc[4] != maxUint32 {
		t.Errorf("Failed to decode %s: got %v", csvstr, nslc)
	}

	invalid := "a,b,cDEf,4,5,6;7;8" // we'll expect some zeroes
	nslc = CsvToU32(invalid)
	if nslc[0] != 0 || nslc[1] != 0 || nslc[2] != 0 || nslc[3] != 4 || nslc[4] != 5 || nslc[5] != 0 {
		t.Errorf("Failed to decode %s: got %v", invalid, nslc)
	}
}

func TestStrsToU32(t *testing.T) {
	rstrs := _randBU32()
	strs := _toStrsU32(rstrs)

	nslc := StrsToU32(strs)

	for i := range nslc {
		if nslc[i] != rstrs[i] {
			t.Errorf("Expected nslc[%d] = randoms[%d]; got %v / %v", i, i, nslc[i], rstrs[i])
		}
	}

	t.Logf("%v == %v", strs, nslc)
}

func _randU32() uint32 {
	m := math.Abs(math.Min(math.Pow(2, 32), math.Pow(2, 32)))

	return uint32(rand.Intn(int(m)))
}

func _randBU32() []uint32 {
	r := make([]uint32, 10)

	for i := 0; i < len(r); i++ {
		r[i] = _randU32()
	}

	return r
}

func _toStrsU32(src []uint32) []string {
	strs := make([]string, len(src))
	for i := range src {
		strs[i] = fmt.Sprintf("%d", src[i])
	}

	return strs
}

var U32_FAST uint32

func BenchmarkFast_U32(b *testing.B) {
	var num uint32
	// generate some random numbers
	x := make([]string, 1000)
	for i := 0; i < 1000; i++ {
		x[i] = fmt.Sprintf("%d", _randU32())
	}

	b.ResetTimer()
	b.ReportAllocs()

	for n := 0; n < b.N; n++ {
		num = ToU32_FAST(x[n*int(1000/b.N)])
	}

	U32_FAST = num
}

var U32_STD uint32

func BenchmarkStdAtoi_U32(b *testing.B) {
	var num uint32
	// generate some random numbers
	x := make([]string, 1000)
	for i := 0; i < 1000; i++ {
		x[i] = fmt.Sprintf("%d", _randU32())
	}

	b.ResetTimer()
	b.ReportAllocs()

	for n := 0; n < b.N; n++ {
		num = ToU32(x[n*int(1000/b.N)])
	}

	U32_STD = num
}
