// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package strings

import (
	"strconv"
	"strings"
)

// ToU64 converts a string to a uint64
// Use only when you don't care if the input is valid, as the error is thrown away.
// No efforts are made to handle overflow.
func ToU64(src string) uint64 {
	num, _ := strconv.ParseUint(src, 10, 64)

	return uint64(num)
}

// ToU64_FAST doesn't use the stdlib to convert numbers.
// It's "safe" if you don't expect negative integers, but really only
// saves 10-20 ns.
func ToU64_FAST(src string) uint64 {
	var n uint64

	for i := 0; i < len(src); i++ {
		n = n*10 + uint64(src[i]-'0')
	}

	return n
}

// CsvToU64 converts a string to []uint64, zero vals included.
func CsvToU64(src string) []uint64 {
	if len(src) == 0 {
		return nil
	}

	split := strings.Split(src, ",")
	r := make([]uint64, len(split))

	for i := 0; i < len(split); i++ {
		r[i] = ToU64(split[i])
	}

	return r
}

// StrsToU64 converts a []string to []uint64.
func StrsToU64(src []string) []uint64 {
	if len(src) == 0 {
		return nil
	}

	r := make([]uint64, len(src))
	for i := range src {
		r[i] = ToU64(src[i])
	}

	return r
}
