// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package strings

import (
	"fmt"
	"math"
	"math/rand"
	"testing"
)

var maxUint64 = ^uint64(0)

func TestU64(t *testing.T) {
	numstr := "100"

	n := ToU64(numstr)
	if n != 100 {
		t.Error("Failed to get 100 from ToU64")
	}

	// we don't _really_ care if the string doesn't actually represent
	// a number. in that case, we just want a 0 back.
	invalid := "-_-f-ado039230_;lol_no<generics>"
	n = ToU64(invalid)
	if n != 0 {
		t.Errorf("Got %d from ToU64, expected 0", n)
	}
}

func TestCsvToU64(t *testing.T) {
	csvstr := fmt.Sprintf("0,1,2,3,%d", maxUint64)

	nslc := CsvToU64(csvstr)
	if nslc[0] != 0 || nslc[1] != 1 || nslc[2] != 2 || nslc[3] != 3 || nslc[4] != maxUint64 {
		t.Errorf("Failed to decode %s: got %v", csvstr, nslc)
	}

	invalid := "a,b,cDEf,4,5,6;7;8" // we'll expect some zeroes
	nslc = CsvToU64(invalid)
	if nslc[0] != 0 || nslc[1] != 0 || nslc[2] != 0 || nslc[3] != 4 || nslc[4] != 5 || nslc[5] != 0 {
		t.Errorf("Failed to decode %s: got %v", invalid, nslc)
	}
}

func TestStrsToU64(t *testing.T) {
	rstrs := _randBU64()
	strs := _toStrsU64(rstrs)

	nslc := StrsToU64(strs)

	for i := range nslc {
		if nslc[i] != rstrs[i] {
			t.Errorf("Expected nslc[%d] = randoms[%d]; got %v / %v", i, i, nslc[i], rstrs[i])
		}
	}

	t.Logf("%v == %v", strs, nslc)
}

func _randU64() uint64 {
	m := math.Abs(math.Min(math.Pow(2, 32), math.Pow(2, 64)))

	return uint64(rand.Intn(int(m)))
}

func _randBU64() []uint64 {
	r := make([]uint64, 10)

	for i := 0; i < len(r); i++ {
		r[i] = _randU64()
	}

	return r
}

func _toStrsU64(src []uint64) []string {
	strs := make([]string, len(src))
	for i := range src {
		strs[i] = fmt.Sprintf("%d", src[i])
	}

	return strs
}

var U64_FAST uint64

func BenchmarkFast_U64(b *testing.B) {
	var num uint64
	// generate some random numbers
	x := make([]string, 1000)
	for i := 0; i < 1000; i++ {
		x[i] = fmt.Sprintf("%d", _randU64())
	}

	b.ResetTimer()
	b.ReportAllocs()

	for n := 0; n < b.N; n++ {
		num = ToU64_FAST(x[n*int(1000/b.N)])
	}

	U64_FAST = num
}

var U64_STD uint64

func BenchmarkStdAtoi_U64(b *testing.B) {
	var num uint64
	// generate some random numbers
	x := make([]string, 1000)
	for i := 0; i < 1000; i++ {
		x[i] = fmt.Sprintf("%d", _randU64())
	}

	b.ResetTimer()
	b.ReportAllocs()

	for n := 0; n < b.N; n++ {
		num = ToU64(x[n*int(1000/b.N)])
	}

	U64_STD = num
}
