// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package strings

import (
	"strconv"
	"strings"
)

// ToU8 converts a string to a uint8
// Use only when you don't care if the input is valid, as the error is thrown away.
// No efforts are made to handle overflow.
func ToU8(src string) uint8 {
	num, _ := strconv.ParseUint(src, 10, 8)

	return uint8(num)
}

// ToU8_FAST doesn't use the stdlib to convert numbers.
// It's "safe" if you don't expect negative integers, but really only
// saves 10-20 ns.
func ToU8_FAST(src string) uint8 {
	var n uint8

	for i := 0; i < len(src); i++ {
		n = n*10 + uint8(src[i]-'0')
	}

	return n
}

// CsvToU8 converts a string to []uint8, zero vals included.
func CsvToU8(src string) []uint8 {
	if len(src) == 0 {
		return nil
	}

	split := strings.Split(src, ",")
	r := make([]uint8, len(split))

	for i := 0; i < len(split); i++ {
		r[i] = ToU8(split[i])
	}

	return r
}

// StrsToU8 converts a []string to []uint8.
func StrsToU8(src []string) []uint8 {
	if len(src) == 0 {
		return nil
	}

	r := make([]uint8, len(src))
	for i := range src {
		r[i] = ToU8(src[i])
	}

	return r
}
