// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package math

func MaxI(a, b int) int {
	if a > b {
		return a
	}

	return b
}

func MinI(a, b int) int {
	if a < b {
		return a
	}

	return b
}
