// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package math

func MaxI16(a, b int16) int16 {
	if a > b {
		return a
	}

	return b
}

func MinI16(a, b int16) int16 {
	if a < b {
		return a
	}

	return b
}
