// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package math

func MaxI32(a, b int32) int32 {
	if a > b {
		return a
	}

	return b
}

func MinI32(a, b int32) int32 {
	if a < b {
		return a
	}

	return b
}
