// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package math

func MaxI64(a, b int64) int64 {
	if a > b {
		return a
	}

	return b
}

func MinI64(a, b int64) int64 {
	if a < b {
		return a
	}

	return b
}
