// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package math

func MaxI8(a, b int8) int8 {
	if a > b {
		return a
	}

	return b
}

func MinI8(a, b int8) int8 {
	if a < b {
		return a
	}

	return b
}
