// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package math

func MaxU(a, b uint) uint {
	if a > b {
		return a
	}

	return b
}

func MinU(a, b uint) uint {
	if a < b {
		return a
	}

	return b
}
