// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package math

func MaxU16(a, b uint16) uint16 {
	if a > b {
		return a
	}

	return b
}

func MinU16(a, b uint16) uint16 {
	if a < b {
		return a
	}

	return b
}
