// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package math

func MaxU32(a, b uint32) uint32 {
	if a > b {
		return a
	}

	return b
}

func MinU32(a, b uint32) uint32 {
	if a < b {
		return a
	}

	return b
}
