// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package math

func MaxU64(a, b uint64) uint64 {
	if a > b {
		return a
	}

	return b
}

func MinU64(a, b uint64) uint64 {
	if a < b {
		return a
	}

	return b
}
