// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package math

import "testing"

func TestU64(t *testing.T) {
	var a, b uint64 = 0, 1

	if MaxU64(a, b) != 1 {
		t.Error("Max fail")
	}

	if MaxU64(b, a) != 1 {
		t.Error("Max fail")
	}

	if MinU64(a, b) != 0 {
		t.Error("Min fail")
	}

	if MinU64(b, a) != 0 {
		t.Error("Min fail")
	}
}
