// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package math

func MaxU8(a, b uint8) uint8 {
	if a > b {
		return a
	}

	return b
}

func MinU8(a, b uint8) uint8 {
	if a < b {
		return a
	}

	return b
}
