// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package math

import "testing"

func TestU16(t *testing.T) {
	var a, b uint16 = 0, 1

	if MaxU16(a, b) != 1 {
		t.Error("Max fail")
	}

	if MaxU16(b, a) != 1 {
		t.Error("Max fail")
	}

	if MinU16(a, b) != 0 {
		t.Error("Min fail")
	}

	if MinU16(b, a) != 0 {
		t.Error("Min fail")
	}
}
