// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package indexof

import (
	"math/rand"
	"testing"
	"time"
)

func TestI16(t *testing.T) {
	rnd := rand.New(rand.NewSource(time.Now().UnixNano()))
	expect := map[int16]int{}

	var Int16s []int16

	c := 0
	for i := 0; i < 256; i++ {
		v := int16(rnd.Int()) // l o l

		// skip if we've already done this one
		if _, ok := expect[v]; ok {
			continue
		}

		Int16s = append(Int16s, v)
		expect[v] = c
		c++
	}

	for i := range expect {
		got := I16(i, Int16s)
		want := expect[i]

		if got != want {
			t.Errorf("Int16(%d) - expected at position %d, got position %d", i, want, got)
		}
	}
}
