// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package indexof

import (
	"math/rand"
	"testing"
	"time"
)

func TestI32(t *testing.T) {
	rnd := rand.New(rand.NewSource(time.Now().UnixNano()))
	expect := map[int32]int{}

	var Int32s []int32

	c := 0
	for i := 0; i < 256; i++ {
		v := int32(rnd.Int()) // l o l

		// skip if we've already done this one
		if _, ok := expect[v]; ok {
			continue
		}

		Int32s = append(Int32s, v)
		expect[v] = c
		c++
	}

	for i := range expect {
		got := I32(i, Int32s)
		want := expect[i]

		if got != want {
			t.Errorf("Int32(%d) - expected at position %d, got position %d", i, want, got)
		}
	}
}
