// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package indexof

import (
	"math/rand"
	"testing"
	"time"
)

func TestI8(t *testing.T) {
	rnd := rand.New(rand.NewSource(time.Now().UnixNano()))
	expect := map[int8]int{}

	var Int8s []int8

	c := 0
	for i := 0; i < 256; i++ {
		v := int8(rnd.Int()) // l o l

		// skip if we've already done this one
		if _, ok := expect[v]; ok {
			continue
		}

		Int8s = append(Int8s, v)
		expect[v] = c
		c++
	}

	for i := range expect {
		got := I8(i, Int8s)
		want := expect[i]

		if got != want {
			t.Errorf("Int8(%d) - expected at position %d, got position %d", i, want, got)
		}
	}
}
