// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package indexof

import (
	"math/rand"
	"testing"
	"time"
)

func TestI(t *testing.T) {
	rnd := rand.New(rand.NewSource(time.Now().UnixNano()))
	expect := map[int]int{}

	var Ints []int

	c := 0
	for i := 0; i < 256; i++ {
		v := int(rnd.Int()) // l o l

		// skip if we've already done this one
		if _, ok := expect[v]; ok {
			continue
		}

		Ints = append(Ints, v)
		expect[v] = c
		c++
	}

	for i := range expect {
		got := I(i, Ints)
		want := expect[i]

		if got != want {
			t.Errorf("Int(%d) - expected at position %d, got position %d", i, want, got)
		}
	}
}
