// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package indexof

import (
	"math/rand"
	"testing"
	"time"
)

func TestU16(t *testing.T) {
	rnd := rand.New(rand.NewSource(time.Now().UnixNano()))
	expect := map[uint16]int{}

	var Uint16s []uint16

	c := 0
	for i := 0; i < 256; i++ {
		v := uint16(rnd.Int()) // l o l

		// skip if we've already done this one
		if _, ok := expect[v]; ok {
			continue
		}

		Uint16s = append(Uint16s, v)
		expect[v] = c
		c++
	}

	for i := range expect {
		got := U16(i, Uint16s)
		want := expect[i]

		if got != want {
			t.Errorf("Uint16(%d) - expected at position %d, got position %d", i, want, got)
		}
	}
}
