// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package indexof

import (
	"math/rand"
	"testing"
	"time"
)

func TestU32(t *testing.T) {
	rnd := rand.New(rand.NewSource(time.Now().UnixNano()))
	expect := map[uint32]int{}

	var Uint32s []uint32

	c := 0
	for i := 0; i < 256; i++ {
		v := uint32(rnd.Int()) // l o l

		// skip if we've already done this one
		if _, ok := expect[v]; ok {
			continue
		}

		Uint32s = append(Uint32s, v)
		expect[v] = c
		c++
	}

	for i := range expect {
		got := U32(i, Uint32s)
		want := expect[i]

		if got != want {
			t.Errorf("Uint32(%d) - expected at position %d, got position %d", i, want, got)
		}
	}
}
