// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package indexof

import (
	"math/rand"
	"testing"
	"time"
)

func TestU64(t *testing.T) {
	rnd := rand.New(rand.NewSource(time.Now().UnixNano()))
	expect := map[uint64]int{}

	var Uint64s []uint64

	c := 0
	for i := 0; i < 256; i++ {
		v := uint64(rnd.Int()) // l o l

		// skip if we've already done this one
		if _, ok := expect[v]; ok {
			continue
		}

		Uint64s = append(Uint64s, v)
		expect[v] = c
		c++
	}

	for i := range expect {
		got := U64(i, Uint64s)
		want := expect[i]

		if got != want {
			t.Errorf("Uint64(%d) - expected at position %d, got position %d", i, want, got)
		}
	}
}
